### ISSUE TITLE
zastávku *** v 'none' neznám

### ISSUE THREAD

**Issue by michlikv** [UFAL-DSG/alex#168] opened 2015-06-11 19:49 UTC
I made Alex say city 'none' again :)

U: chci jet do zastávky Donovalská 
(inform(to_stop="Donovalská"))
S: Dobře, do zastávky Donovalská. Z jaké zastávky chcete jet? 
(iconfirm(to_stop="Donovalská")&request(from_stop))
U: chci jet ze zastávky Lázně
(inform(from_stop="Lázně"))
S: Do Prahy. Promiňte, asi Vám nerozumím. Zastávku Lázně v none neznám.
(iconfirm(to_city="Praha")&apology()&inform(stops_conflict="incompatible")&inform(from_city="none")&inform(from_stop="Lázně"))

I made her say it from shub with google directions, from thub with hdc slu and google directions and also live alex on phone, just for sure :)

I remember this used to be an issue, but I thought it does not happen anymore... I got this in 6/100 dialogues with random stops.

**Comment by tuetschek** [comment] 2015-06-16 08:54
@michlikv : #169 has been merged into master. Can you please confirm that the issue is resolved so that we can close this?

**Closed** 2015-06-16 10:55 UTC
